### ISSUE TITLE
Command to create a post

### ISSUE THREAD

**Issue by ProjectMoon** [justlark/gempost#1]
I think it would be a good idea to add a `gempost create` type command for creating new posts in the blog, as the posts require a secondary YAML file to be created, with the recommendation of setting a UUID as the unique identifier. While it's not difficult to do by hand, this could benefit greatly from automation.

**Comment by justlark** [comment]
Excellent idea! I'll get on it.

**Comment by justlark** [comment]
Done and published as v0.2.0. Thanks for the suggestion!

**Comment by ProjectMoon** [comment]
Works perfectly. Great job! Small suggestion: maybe an optional switch to add the title to the YAML file?

**Comment by justlark** [comment]
Hmm, also a good suggestion. I'll add that as well

**Comment by justlark** [comment]
Alright, I added a `-t, --title` switch. How's that?

**Comment by ProjectMoon** [comment]
Exactly what I was thinking. (Of course, now needs a new release)

**Comment by justlark** [comment]
Thankfully version numbers are free lol
